name: real_estate_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  animated_bottom_navigation_bar: ^1.3.3
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  google_maps_flutter:
  bitmap: ^0.2.0
  widget_to_marker:
  font_awesome_flutter:
  animated_text_kit: ^4.2.2
  countup: ^0.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json_assets/
  fonts:
    - family: Euclid
      fonts:
        - asset: assets/fonts/Euclid/Euclid Circular A Bold.ttf
          weight: 700
        - asset: assets/fonts/Euclid/Euclid Circular A Bold Italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Euclid/Euclid Circular A Italic.ttf
          style: italic
        - asset: assets/fonts/Euclid/Euclid Circular A Light.ttf
          weight: 300
        - asset: assets/fonts/Euclid/Euclid Circular A Light Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Euclid/Euclid Circular A Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid/Euclid Circular A Medium Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Euclid/Euclid Circular A Regular.ttf
        - asset: assets/fonts/Euclid/Euclid Circular A SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid/Euclid Circular A SemiBold Italic.ttf
          weight: 600
          style: italic

